FROM python

WORKDIR /app


COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN nohup python SystemApi.py > nohup.out 2>&1 &



COPY . .

EXPOSE 31706


CMD ["nohup", "python", "SystemApi.py", "> nohup.out 2>&1"]
