FROM python

WORKDIR /app

COPY IranianSansBold.ttf arial.ttf /app/fonts/ 

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt


COPY . .

CMD [ "python","-u","Labelmain.py"] 